"""
WordPress Publish Skill - Publishes content to WordPress via REST API.

Uses WordPress Application Password authentication (WordPress 5.6+).

To create an Application Password:
    WordPress Admin → Users → Profile → scroll to "Application Passwords"
    Enter a name, click "Add New Application Password", copy the generated password.

Environment variables:
    WORDPRESS_URL          WordPress site URL (e.g. https://example.com)
    WORDPRESS_USERNAME     WordPress username
    WORDPRESS_APP_PASSWORD Application password (spaces are stripped automatically)
"""

import logging
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import httpx

logger = logging.getLogger(__name__)


# ------------------------------------------------------------------
# Inline helpers
# ------------------------------------------------------------------

def _inline_md(text: str) -> str:
    """Convert inline markdown to HTML (bold, italic, code, links)."""
    text = re.sub(r"\*\*\*(.+?)\*\*\*", r"<strong><em>\1</em></strong>", text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    return text


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


@dataclass
class WordPressPublishResult:
    """Result of a WordPress publish operation."""
    success: bool
    post_id: Optional[int] = None
    post_url: Optional[str] = None
    edit_url: Optional[str] = None
    status: Optional[str] = None
    error: Optional[str] = None


@dataclass
class WordPressConnectionInfo:
    """Result of a WordPress connection verification."""
    connected: bool
    site_url: Optional[str] = None
    site_name: Optional[str] = None
    user_id: Optional[int] = None
    username: Optional[str] = None
    error: Optional[str] = None


class WordPressPublishSkill:
    """
    Publishes content to WordPress using the REST API.

    Supports:
    - Publishing as draft or live post
    - Markdown-to-HTML conversion
    - Category and tag resolution by name (creates if missing)
    - Featured image assignment by attachment ID
    - Connection verification
    """

    def __init__(
        self,
        wp_url: str,
        username: str,
        app_password: str,
        timeout: int = 30,
    ):
        """
        Initialize the WordPress publish skill.

        Args:
            wp_url: WordPress site URL (e.g. https://example.com)
            username: WordPress username
            app_password: Application password (spaces stripped automatically)
            timeout: HTTP request timeout in seconds
        """
        self.wp_url = wp_url.rstrip("/")
        self.username = username
        self.app_password = app_password.replace(" ", "")
        self.timeout = timeout
        self._base_url = f"{self.wp_url}/wp-json/wp/v2"

    # ------------------------------------------------------------------
    # Core publish
    # ------------------------------------------------------------------

    async def publish(
        self,
        title: str,
        content: str,
        status: str = "draft",
        excerpt: Optional[str] = None,
        category_ids: Optional[List[int]] = None,
        tag_ids: Optional[List[int]] = None,
        slug: Optional[str] = None,
        featured_media: Optional[int] = None,
        meta: Optional[Dict[str, Any]] = None,
    ) -> WordPressPublishResult:
        """
        Create a post on WordPress.

        Args:
            title: Post title (plain text)
            content: Post body (HTML)
            status: "draft" | "publish" | "pending" | "private"
            excerpt: Optional excerpt (plain text)
            category_ids: List of category IDs
            tag_ids: List of tag IDs
            slug: URL slug (auto-generated by WordPress if omitted)
            featured_media: Attachment ID for featured image
            meta: Optional dict of post meta fields

        Returns:
            WordPressPublishResult
        """
        payload: Dict[str, Any] = {
            "title": title,
            "content": content,
            "status": status,
        }
        if excerpt:
            payload["excerpt"] = excerpt
        if category_ids:
            payload["categories"] = category_ids
        if tag_ids:
            payload["tags"] = tag_ids
        if slug:
            payload["slug"] = slug
        if featured_media:
            payload["featured_media"] = featured_media
        if meta:
            payload["meta"] = meta

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.post(
                    f"{self._base_url}/posts",
                    auth=(self.username, self.app_password),
                    json=payload,
                )

            if response.status_code in (200, 201):
                data = response.json()
                post_id = data["id"]
                return WordPressPublishResult(
                    success=True,
                    post_id=post_id,
                    post_url=data.get("link", ""),
                    edit_url=f"{self.wp_url}/wp-admin/post.php?post={post_id}&action=edit",
                    status=data.get("status", status),
                )

            error_detail = _extract_error(response)
            logger.error(f"WordPress API {response.status_code}: {error_detail}")
            return WordPressPublishResult(
                success=False,
                error=f"HTTP {response.status_code}: {error_detail}",
            )

        except httpx.TimeoutException:
            return WordPressPublishResult(success=False, error="Request timed out")
        except Exception as e:
            logger.error(f"WordPress publish failed: {e}")
            return WordPressPublishResult(success=False, error=str(e))

    # ------------------------------------------------------------------
    # Category / tag helpers
    # ------------------------------------------------------------------

    async def get_categories(self) -> List[Dict[str, Any]]:
        """Fetch all categories (up to 100)."""
        return await self._get_terms("categories")

    async def get_tags(self) -> List[Dict[str, Any]]:
        """Fetch all tags (up to 100)."""
        return await self._get_terms("tags")

    async def _get_terms(self, taxonomy: str) -> List[Dict[str, Any]]:
        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.get(
                    f"{self._base_url}/{taxonomy}",
                    auth=(self.username, self.app_password),
                    params={"per_page": 100},
                )
                response.raise_for_status()
                return response.json()
        except Exception as e:
            logger.error(f"Failed to fetch {taxonomy}: {e}")
            return []

    async def resolve_category_names(self, names: List[str]) -> List[int]:
        """
        Resolve category names to IDs, creating any that don't exist.

        Args:
            names: List of category names

        Returns:
            List of category IDs
        """
        if not names:
            return []
        categories = await self.get_categories()
        name_to_id = {c["name"].lower(): c["id"] for c in categories}
        name_to_id.update({c["slug"]: c["id"] for c in categories})

        ids = []
        for name in names:
            key = name.lower()
            if key in name_to_id:
                ids.append(name_to_id[key])
            else:
                cat_id = await self._create_term("categories", name)
                if cat_id:
                    ids.append(cat_id)
        return ids

    async def resolve_tag_names(self, names: List[str]) -> List[int]:
        """
        Resolve tag names to IDs, creating any that don't exist.

        Args:
            names: List of tag names

        Returns:
            List of tag IDs
        """
        if not names:
            return []
        tags = await self.get_tags()
        name_to_id = {t["name"].lower(): t["id"] for t in tags}

        ids = []
        for name in names:
            key = name.lower()
            if key in name_to_id:
                ids.append(name_to_id[key])
            else:
                tag_id = await self._create_term("tags", name)
                if tag_id:
                    ids.append(tag_id)
        return ids

    async def _create_term(self, taxonomy: str, name: str) -> Optional[int]:
        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.post(
                    f"{self._base_url}/{taxonomy}",
                    auth=(self.username, self.app_password),
                    json={"name": name},
                )
                if response.status_code in (200, 201):
                    return response.json()["id"]
                logger.warning(
                    f"Could not create {taxonomy} '{name}': {_extract_error(response)}"
                )
        except Exception as e:
            logger.error(f"Failed to create {taxonomy} '{name}': {e}")
        return None

    # ------------------------------------------------------------------
    # Connection verification
    # ------------------------------------------------------------------

    async def verify_connection(self) -> WordPressConnectionInfo:
        """
        Verify WordPress credentials and REST API access.

        Returns:
            WordPressConnectionInfo with site and user details on success.
        """
        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                # Check user auth
                user_resp = await client.get(
                    f"{self._base_url}/users/me",
                    auth=(self.username, self.app_password),
                )
                if user_resp.status_code != 200:
                    return WordPressConnectionInfo(
                        connected=False,
                        error=f"Authentication failed: {_extract_error(user_resp)}",
                    )
                user = user_resp.json()

                # Get site info
                site_resp = await client.get(f"{self.wp_url}/wp-json/")
                site_name = None
                if site_resp.status_code == 200:
                    site_name = site_resp.json().get("name")

            return WordPressConnectionInfo(
                connected=True,
                site_url=self.wp_url,
                site_name=site_name,
                user_id=user.get("id"),
                username=user.get("name"),
            )
        except httpx.ConnectError:
            return WordPressConnectionInfo(
                connected=False,
                error=f"Could not connect to {self.wp_url}",
            )
        except Exception as e:
            return WordPressConnectionInfo(connected=False, error=str(e))

    # ------------------------------------------------------------------
    # Gutenberg block conversion
    # ------------------------------------------------------------------

    @staticmethod
    def markdown_to_blocks(content: str) -> str:
        """
        Convert Markdown to WordPress Gutenberg block markup (WP 5.0+).

        Each structural element is wrapped in block comment delimiters
        so the block editor recognises and renders them natively.
        Inline markdown (bold, italic, code, links) is converted to HTML.
        """
        lines = content.split("\n")
        blocks: list[str] = []
        i = 0

        while i < len(lines):
            line = lines[i]

            # Heading
            m = re.match(r"^(#{1,6})\s+(.+)", line)
            if m:
                level = len(m.group(1))
                text = _inline_md(m.group(2))
                level_attr = "" if level == 2 else f' {{"level":{level}}}'
                blocks.append(
                    f'<!-- wp:heading{level_attr} -->\n'
                    f'<h{level} class="wp-block-heading">{text}</h{level}>\n'
                    f'<!-- /wp:heading -->'
                )
                i += 1
                continue

            # Horizontal rule
            if re.match(r"^[-*_]{3,}\s*$", line):
                blocks.append(
                    '<!-- wp:separator -->\n'
                    '<hr class="wp-block-separator has-alpha-channel-opacity"/>\n'
                    '<!-- /wp:separator -->'
                )
                i += 1
                continue

            # Fenced code block
            if line.startswith("```"):
                lang = line[3:].strip()
                code_lines: list[str] = []
                i += 1
                while i < len(lines) and not lines[i].startswith("```"):
                    code_lines.append(lines[i])
                    i += 1
                code = _escape_html("\n".join(code_lines))
                lang_attr = f' {{"language":"{lang}"}}' if lang else ""
                blocks.append(
                    f'<!-- wp:code{lang_attr} -->\n'
                    f'<pre class="wp-block-code"><code>{code}</code></pre>\n'
                    f'<!-- /wp:code -->'
                )
                i += 1  # skip closing ```
                continue

            # Blockquote
            if line.startswith("> "):
                quote_lines: list[str] = []
                while i < len(lines) and lines[i].startswith("> "):
                    quote_lines.append(_inline_md(lines[i][2:]))
                    i += 1
                inner = " ".join(quote_lines)
                blocks.append(
                    '<!-- wp:quote -->\n'
                    f'<blockquote class="wp-block-quote"><p>{inner}</p></blockquote>\n'
                    '<!-- /wp:quote -->'
                )
                continue

            # Unordered list
            if re.match(r"^[-*+]\s+", line):
                items: list[str] = []
                while i < len(lines) and re.match(r"^[-*+]\s+", lines[i]):
                    text = _inline_md(re.sub(r"^[-*+]\s+", "", lines[i]))
                    items.append(
                        f'<!-- wp:list-item -->\n<li>{text}</li>\n<!-- /wp:list-item -->'
                    )
                    i += 1
                inner = "\n".join(items)
                blocks.append(
                    '<!-- wp:list -->\n'
                    f'<ul class="wp-block-list">\n{inner}\n</ul>\n'
                    '<!-- /wp:list -->'
                )
                continue

            # Ordered list
            if re.match(r"^\d+\.\s+", line):
                items = []
                while i < len(lines) and re.match(r"^\d+\.\s+", lines[i]):
                    text = _inline_md(re.sub(r"^\d+\.\s+", "", lines[i]))
                    items.append(
                        f'<!-- wp:list-item -->\n<li>{text}</li>\n<!-- /wp:list-item -->'
                    )
                    i += 1
                inner = "\n".join(items)
                blocks.append(
                    '<!-- wp:list {"ordered":true} -->\n'
                    f'<ol>\n{inner}\n</ol>\n'
                    '<!-- /wp:list -->'
                )
                continue

            # Blank line — skip
            if not line.strip():
                i += 1
                continue

            # Paragraph — collect until blank line or block-level marker
            _BLOCK_START = re.compile(r"^(#{1,6}\s|[-*+]\s|\d+\.\s|```|>|[-*_]{3,}\s*$)")
            para_lines: list[str] = []
            while i < len(lines) and lines[i].strip() and not _BLOCK_START.match(lines[i]):
                para_lines.append(lines[i])
                i += 1
            if para_lines:
                text = _inline_md(" ".join(para_lines))
                blocks.append(
                    '<!-- wp:paragraph -->\n'
                    f'<p>{text}</p>\n'
                    '<!-- /wp:paragraph -->'
                )

        return "\n\n".join(blocks)

    @staticmethod
    def markdown_to_html(content: str) -> str:
        """Convert markdown to plain HTML (legacy; prefer markdown_to_blocks for WP 6+)."""
        try:
            import markdown as md_lib
            return md_lib.markdown(content, extensions=["extra", "toc"])
        except ImportError:
            pass
        html = content
        html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
        html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
        html = re.sub(r"^# (.+)$", r"<h1>\1</h1>", html, flags=re.MULTILINE)
        html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
        html = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html)
        html = re.sub(r"`(.+?)`", r"<code>\1</code>", html)
        paragraphs = html.split("\n\n")
        wrapped = []
        for p in paragraphs:
            p = p.strip()
            if not p:
                continue
            if re.match(r"^<(h[1-6]|ul|ol|li|blockquote|pre)", p):
                wrapped.append(p)
            else:
                wrapped.append(f"<p>{p}</p>")
        return "\n\n".join(wrapped)


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def _extract_error(response: httpx.Response) -> str:
    """Extract a readable error message from a WordPress API response."""
    try:
        data = response.json()
        return data.get("message", response.text[:200])
    except Exception:
        return response.text[:200]
