"""
Example usage of the Creation Agent with complete workflow.

This script demonstrates:
1. Complete Research → Brief → Creation workflow
2. Long-form content generation
3. Social media content generation
4. Multiple content variations
5. Brand voice validation
"""

import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from agents.research.research import ResearchAgent
from agents.creation.creation import CreationAgent
from skills.content_brief.content_brief import ContentBriefSkill
from skills.long_form_writing.long_form_writing import LongFormWritingSkill
from skills.social_content.social_content import SocialContentSkill
from agents.base.models import (
    ContentType, ToneType, Source, ResearchBrief, ContentBrief
)
import json


def example_1_complete_workflow():
    """
    Example 1: Complete workflow from research to article creation.
    """
    print("\n" + "="*80)
    print("EXAMPLE 1: Complete Research → Brief → Creation Workflow")
    print("="*80 + "\n")

    # Step 1: Research (simulated with realistic data)
    print("Step 1: Research Phase")
    print("-" * 40)

    research_agent = ResearchAgent()

    # Simulate research results
    simulated_sources = [
        Source(
            url="https://arxiv.org/paper/ai-agents-2024",
            title="Multi-Agent Systems in Modern AI",
            author="Dr. Sarah Chen",
            publication_date="2024-03-15",
            credibility_score=0.95,
            key_quotes=[
                "Collaborative AI agents can improve efficiency by 45%",
                "Specialized agents handling different aspects produce higher quality outputs"
            ],
            key_facts=[
                "Research shows that collaborative AI agents can improve content generation efficiency by 45%",
                "The study found that specialized agents handling different aspects of content creation produce higher quality outputs than monolithic systems",
                "Agent-based systems reduce production time while maintaining consistency across deliverables"
            ]
        ),
        Source(
            url="https://techcrunch.com/2024/ai-workflow-automation",
            title="Workflow Automation with AI Agents",
            author="John Martinez",
            publication_date="2024-02-20",
            credibility_score=0.90,
            key_quotes=[
                "Companies report 60% faster content production"
            ],
            key_facts=[
                "Companies using multi-agent systems report 60% faster content production",
                "The technology enables parallel processing of research and writing tasks",
                "Experts predict that 80% of routine content will be agent-generated by 2025"
            ]
        )
    ]

    research_brief = ResearchBrief(
        topic="AI agents for content creation automation",
        sources=simulated_sources,
        key_findings=[
            "Multi-agent systems significantly improve content creation efficiency",
            "Specialized agents produce higher quality outputs",
            "Agent-based automation is becoming the industry standard",
            "Parallel processing enables faster content production",
            "Agent coordination is key to maintaining consistency"
        ],
        data_points={
            "source_count": 2,
            "high_credibility_sources": 2,
            "average_credibility": 0.925,
            "statistics_found": ["45%", "60%", "80%"]
        },
        research_gaps=[]
    )

    print(f"✓ Research completed")
    print(f"  Sources: {len(research_brief.sources)}")
    print(f"  Key findings: {len(research_brief.key_findings)}")
    print(f"  Credibility: {research_brief.data_points['average_credibility']:.2f}\n")

    # Step 2: Content Brief
    print("Step 2: Content Brief Creation")
    print("-" * 40)

    brief_skill = ContentBriefSkill()

    content_brief = brief_skill.execute(
        research_brief=research_brief,
        content_type=ContentType.ARTICLE,
        target_audience="Marketing professionals and content creators"
    )

    print(f"✓ Content brief created")
    print(f"  Content type: {content_brief.content_type.value}")
    print(f"  Target audience: {content_brief.target_audience}")
    print(f"  Key messages: {len(content_brief.key_messages)}")
    print(f"  Tone: {content_brief.tone.value}")
    print(f"  Word count target: {content_brief.word_count_range}\n")

    # Step 3: Content Creation
    print("Step 3: Content Creation")
    print("-" * 40)

    creation_agent = CreationAgent()

    draft = creation_agent.process({"content_brief": content_brief})

    print(f"✓ Article created")
    print(f"  Word count: {draft.word_count}")
    print(f"  Format: {draft.format}")
    print(f"  Within target: {content_brief.word_count_range[0]} <= {draft.word_count} <= {content_brief.word_count_range[1]}")

    # Validate
    is_valid, errors = draft.validate()
    if is_valid:
        print(f"  ✓ Validation passed")
    else:
        print(f"  ⚠ Validation warnings: {errors}")

    print(f"\n{'='*80}")
    print("GENERATED ARTICLE PREVIEW")
    print('='*80)
    print(draft.content[:800] + "\n\n[... article continues ...]")
    print('='*80)


def example_2_social_content():
    """
    Example 2: Generate social media content for multiple platforms.
    """
    print("\n" + "="*80)
    print("EXAMPLE 2: Social Media Content Generation")
    print("="*80 + "\n")

    # Create a content brief for social
    social_brief = ContentBrief(
        content_type=ContentType.SOCIAL_POST,
        target_audience="Technology professionals and business leaders",
        key_messages=[
            "AI-powered content automation is transforming how teams work",
            "Multi-agent systems boost productivity by 45%",
            "Companies are seeing 60% faster content production"
        ],
        tone=ToneType.PROFESSIONAL,
        structure_requirements=["Hook", "Main message", "Call to action"],
        word_count_range=(50, 300),
        seo_keywords=["AI", "ContentAutomation", "Productivity", "AgentSystems"],
        brand_guidelines={}
    )

    creation_agent = CreationAgent()
    social_skill = SocialContentSkill()

    platforms = ["linkedin", "twitter", "instagram"]

    for platform in platforms:
        print(f"\n{platform.upper()} Post")
        print("-" * 40)

        # Generate platform-specific content
        input_data = {
            "content_brief": social_brief,
            "additional_context": {"platform": platform}
        }

        draft = creation_agent.process(input_data)

        specs = social_skill.platform_specs[platform]

        print(f"Character count: {len(draft.content)} / {specs['max_length']}")
        print(f"Optimal range: {specs['optimal_length']}")
        print(f"\nContent:\n")
        print(draft.content)
        print()


def example_3_long_form_structures():
    """
    Example 3: Generate long-form content with different structures.
    """
    print("\n" + "="*80)
    print("EXAMPLE 3: Long-Form Content with Different Structures")
    print("="*80 + "\n")

    # Create content brief
    brief = ContentBrief(
        content_type=ContentType.ARTICLE,
        target_audience="Software developers",
        key_messages=[
            "Understanding multi-agent architecture is crucial for modern development",
            "Agent coordination patterns enable scalable systems",
            "Proper handoff protocols ensure data consistency",
            "Quality gates validate output at each stage"
        ],
        tone=ToneType.TECHNICAL,
        structure_requirements=[
            "Introduction with hook",
            "Architecture overview",
            "Implementation patterns",
            "Best practices",
            "Conclusion"
        ],
        word_count_range=(800, 1200),
        seo_keywords=["multi-agent", "architecture", "coordination"],
        brand_guidelines={}
    )

    skill = LongFormWritingSkill()

    structures = ["problem_solution", "how_to", "analysis"]

    for structure_type in structures:
        print(f"\n{structure_type.upper().replace('_', ' ')} Structure")
        print("-" * 40)

        content = skill.execute(brief, structure_type=structure_type)

        word_count = len(content.split())
        print(f"Word count: {word_count}")
        print(f"\nPreview (first 300 chars):")
        print(content[:300] + "...\n")


def example_4_brand_voice_validation():
    """
    Example 4: Brand voice validation and compliance checking.
    """
    print("\n" + "="*80)
    print("EXAMPLE 4: Brand Voice Validation")
    print("="*80 + "\n")

    # Create brief with brand guidelines
    brief = ContentBrief(
        content_type=ContentType.BLOG_POST,
        target_audience="Marketing professionals",
        key_messages=[
            "AI agents revolutionize content workflows",
            "Automation boosts team productivity significantly",
            "Smart systems enable better content quality"
        ],
        tone=ToneType.PROFESSIONAL,
        structure_requirements=["Introduction", "Main content", "Conclusion"],
        word_count_range=(600, 900),
        seo_keywords=["AI", "automation", "productivity"],
        brand_guidelines={
            "preferred_terms": ["AI agents", "automation", "workflow", "productivity"],
            "avoided_terms": ["robots", "artificial intelligence bots", "cyborg"],
            "tone": "professional"
        }
    )

    # Create content with brand checking enabled
    agent = CreationAgent(config={"enable_brand_check": True})

    draft = agent.process({"content_brief": brief})

    print("Brand Voice Analysis")
    print("-" * 40)
    print(f"Score: {draft.metadata.get('brand_voice_score', 'N/A'):.2f}")
    print(f"Passed: {draft.metadata.get('brand_voice_passed', 'N/A')}")

    if draft.metadata.get('brand_voice_score', 1.0) < 0.7:
        print(f"\n⚠ Brand voice issues detected")
    else:
        print(f"\n✓ Brand voice validation passed")

    print(f"\nContent preview (first 200 chars):")
    print(draft.content[:200] + "...")


def example_5_content_variations():
    """
    Example 5: Generate multiple content variations for A/B testing.
    """
    print("\n" + "="*80)
    print("EXAMPLE 5: Content Variations for A/B Testing")
    print("="*80 + "\n")

    brief = ContentBrief(
        content_type=ContentType.BLOG_POST,
        target_audience="Business leaders",
        key_messages=[
            "AI automation drives business growth",
            "Smart content systems save time and resources",
            "Early adopters gain competitive advantage"
        ],
        tone=ToneType.PERSUASIVE,
        structure_requirements=["Hook", "Problem", "Solution", "Benefits", "CTA"],
        word_count_range=(600, 800),
        seo_keywords=["AI", "automation", "business growth"],
        brand_guidelines={}
    )

    agent = CreationAgent()

    print("Generating 3 variations...\n")

    variations = agent.generate_variations(brief, count=3)

    for i, var in enumerate(variations, 1):
        print(f"Variation {i}")
        print("-" * 40)
        print(f"Word count: {var.word_count}")
        print(f"Variation ID: {var.metadata.get('variation_id')}")
        print(f"\nOpening (first 150 chars):")
        print(var.content[:150] + "...\n")


def example_6_twitter_thread():
    """
    Example 6: Generate Twitter thread from content brief.
    """
    print("\n" + "="*80)
    print("EXAMPLE 6: Twitter Thread Generation")
    print("="*80 + "\n")

    brief = ContentBrief(
        content_type=ContentType.SOCIAL_POST,
        target_audience="Tech enthusiasts and developers",
        key_messages=[
            "Multi-agent systems are changing how we build software",
            "Each agent specializes in one task - research, writing, or production",
            "Agent coordination ensures consistency across outputs",
            "This approach improves efficiency by 45%",
            "The future of content creation is agent-based collaboration"
        ],
        tone=ToneType.CONVERSATIONAL,
        structure_requirements=["Thread format"],
        word_count_range=(280, 1400),
        seo_keywords=["AI", "MultiAgent", "Software"],
        brand_guidelines={}
    )

    skill = SocialContentSkill()

    thread = skill.execute(
        content_brief=brief,
        platform="twitter",
        format_type="thread"
    )

    print("Twitter Thread:")
    print("-" * 40)
    print(thread)


def main():
    """Run all examples."""
    print("\n" + "="*80)
    print("CREATION AGENT EXAMPLES")
    print("="*80)

    try:
        example_1_complete_workflow()
        example_2_social_content()
        example_3_long_form_structures()
        example_4_brand_voice_validation()
        example_5_content_variations()
        example_6_twitter_thread()

        print("\n" + "="*80)
        print("ALL EXAMPLES COMPLETED SUCCESSFULLY")
        print("="*80 + "\n")

    except Exception as e:
        print(f"\n✗ Example failed with error: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
